name: OSS Scan
jobs:
  fossa-scan:
   uses: splunk/oss-scanning/.github/workflows/oss-scan.yml@main
   secrets: inherit
on:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - opened
